# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: NJMMBuild
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: [4.1]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@b75d3e0c21718c20529373a7dd35ff5e1c1a5759
        with:
          r-version: ${{ matrix.r-version }}
          Ncpus: 4
      - uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-libs-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-libs-
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          rm '/usr/local/bin/gfortran'
          brew install pkg-config gdal proj geos
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('rsconnect', 'testthat', 'renv'))"
          Rscript -e "renv::consent(provided = TRUE)"
          Rscript -e "renv::restore()"
      - name: Run Tests
        run: |
          Rscript test/testthat.R